# Generated by Django 5.2.1 on 2025-05-13 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank.', 'unique': 'This ID has already been used.'}, max_length=15, unique=True, validators=[django.core.validators.MaxLengthValidator(15), django.core.validators.MinLengthValidator(8)]),
        ),
    ]
