# Generated by Django 5.2.1 on 2025-05-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='amount',
            new_name='points',
        ),
    ]
