# Generated by Django 5.2.1 on 2025-05-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_amount_debt_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.TextField(default='No name'),
        ),
    ]
