# Generated by Django 5.2.1 on 2025-05-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='name',
            field=models.TextField(default='No name'),
        ),
    ]
