# Generated by Django 5.2.1 on 2025-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_debt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid_off',
            field=models.BooleanField(default=False),
        ),
    ]
