# Generated by Django 5.2.1 on 2025-05-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_debt_paid_off'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='paid_off',
            new_name='paid',
        ),
    ]
